# Import Packages Needed

In [1]:
%load_ext autoreload
%autoreload 2
import copy
import os
import pandas as pd
import matplotlib.pyplot as plt
import tsam.timeseriesaggregation as tsam
import numpy as np
%matplotlib inline

# Import E-Demand for 2 Regions and 4 Regions Respectively

In [2]:
edem2=pd.read_excel('differently aggregated regions/2 regions/electricityDemand.xlsx', index_col = 0)

In [3]:
edem4=pd.read_excel('differently aggregated regions/4 regions/electricityDemand.xlsx', index_col = 0)

### Reset Index to Daytime for TSAM

In [4]:
edem2.index = pd.date_range('2050-01-01 00:30:00', periods=edem2.shape[0],
                                             freq='1H', tz='Europe/Berlin')

In [5]:
edem4.index = pd.date_range('2050-01-01 00:30:00', periods=edem4.shape[0],
                                             freq='1H', tz='Europe/Berlin')

# Cluster to Emphasize that Different Spatial Aggregation Leads to Different Sequence

In [6]:
aggregationEdem2 = tsam.TimeSeriesAggregation(edem2, noTypicalPeriods = 12, hoursPerPeriod = 24, 
                                        clusterMethod = 'hierarchical')

In [7]:
aggregationEdem4 = tsam.TimeSeriesAggregation(edem4, noTypicalPeriods = 12, hoursPerPeriod = 24, 
                                        clusterMethod = 'hierarchical')

In [8]:
typPeriodsEdem2 = aggregationEdem2.createTypicalPeriods()
typPeriodsEdem4 = aggregationEdem4.createTypicalPeriods()

In [9]:
predictedPeriodsEdem2 = aggregationEdem2.predictOriginalData()
predictedPeriodsEdem4 = aggregationEdem4.predictOriginalData()

In [10]:
aggregationEdem2.clusterOrder

array([10,  2,  2,  2,  5,  6,  9,  0,  0,  0,  0,  1,  5,  0,  4,  4,  4,
        4,  1,  5,  0,  4,  4,  4,  4,  1,  5,  0,  0,  0,  0,  0,  1,  5,
        9,  0,  4,  4,  0,  1,  5,  0,  4,  4,  4,  4,  1,  5,  0,  0,  0,
        4,  0,  1,  5,  0,  4,  4,  0,  0,  1,  6,  0,  0,  0,  0,  0,  1,
        6,  0,  4,  0,  0,  0,  1,  6,  9,  0,  0,  0,  0,  1,  5,  0,  0,
        0,  0,  5,  5,  6,  6,  3,  0,  0,  0,  1,  5,  9,  0,  0,  0,  3,
        8,  6, 11,  9,  9,  3,  3,  8,  6, 11,  3,  9,  9,  3,  8,  6, 11,
        3,  6, 11,  3,  8,  6, 11,  9,  3,  6,  2,  8,  6, 11,  3,  3,  3,
        3,  8, 10, 10, 11,  3,  3,  3,  8,  6, 11,  3,  3,  8,  2,  8, 10,
       11,  3,  3,  3,  3,  8, 10, 11,  3,  3,  3,  2,  8, 10, 11,  3,  3,
        3,  3,  8, 10, 11,  3,  2,  3,  3,  8, 10, 11,  3,  3,  3,  3,  8,
       10, 11,  3,  3,  3,  3,  8, 10, 11,  3,  3,  3,  3,  8, 10, 11,  3,
        3,  3,  3,  8,  6, 11,  2,  2,  3,  3,  8,  6, 11,  3,  3,  3,  3,
        8,  6, 11,  3,  3

In [11]:
aggregationEdem4.clusterOrder

array([ 7,  3,  3,  3,  3,  3,  9,  9,  9, 10, 10,  3,  3,  9,  9, 10, 10,
       10,  3,  3,  9,  9,  9,  9,  9,  4,  4,  9,  9,  9,  9,  9,  4,  3,
       10,  5, 10, 10, 10,  3,  3, 10, 10, 10,  2,  2,  4,  3,  1,  1,  1,
        2,  1,  3,  3,  1,  2,  2,  1,  1,  4,  7,  0,  0,  5,  1,  1,  4,
        7,  1,  2,  1,  1,  1,  4,  7,  1,  1,  1,  1,  1,  4,  4,  1,  1,
        1,  1,  3,  6,  7,  7,  0,  1,  1,  1,  4,  7,  0,  1,  1,  1,  0,
        6, 11,  8,  0,  0,  0,  0,  6, 11,  0,  0,  8,  0,  0,  6, 11,  0,
        0, 11,  0,  8,  6, 11,  8,  0,  0, 11,  0,  6, 11,  0,  0,  8,  8,
        8,  6, 11, 11,  0,  0,  8,  8,  6,  7,  0,  5,  8,  6,  0,  6,  7,
        0,  0,  0,  0,  0,  6,  7,  0,  0,  0,  0,  0,  6,  7,  0,  0,  0,
        0,  0,  6,  7,  0,  0,  0,  0,  0,  6,  7,  0,  0,  0,  0,  0,  6,
       11,  8,  8,  0,  0,  0, 11, 11,  8,  8,  8,  8,  8, 11, 11,  8,  8,
        8,  0,  0,  6,  7,  0,  0,  0,  0,  0,  6,  7,  0,  0,  0,  0,  0,
        6,  7,  0,  0,  0

### Means Remain

For 2 regions:

In [12]:
edem2.mean(axis=0)

cluster_0    26.980326
cluster_1    33.282231
dtype: float64

In [13]:
predictedPeriodsEdem2.mean(axis=0)

cluster_0    26.980326
cluster_1    33.282231
dtype: float64

For 4 regions:

In [14]:
edem4.mean(axis=0)

cluster_0    24.108759
cluster_1    10.753967
cluster_2     9.344134
cluster_3    16.055696
dtype: float64

In [15]:
predictedPeriodsEdem4.mean(axis=0)

cluster_0    24.108759
cluster_1    10.753967
cluster_2     9.344134
cluster_3    16.055696
dtype: float64

# Now Aggregating with Kept Sequence from E-Demand from 4 Regions for 2 Regions

In [16]:
aggregationEdem2.clusterCenterIndices

[77, 46, 211, 182, 350, 320, 117, 288, 221, 254, 194, 121]

In [17]:
aggregationEdem4.clusterCenterIndices

[184, 79, 322, 19, 348, 64, 158, 250, 198, 20, 37, 110]

### Cluster Again with Given Sequences

In [18]:
aggregationEdem2Predef = tsam.TimeSeriesAggregation(edem2, noTypicalPeriods = 12, hoursPerPeriod = 24, 
                                        clusterMethod = 'hierarchical', 
                                        predefClusterOrder=aggregationEdem2.clusterOrder,
                                        predefClusterCenterIndices=aggregationEdem2.clusterCenterIndices)

In [19]:
aggregationEdem4Predef = tsam.TimeSeriesAggregation(edem4, noTypicalPeriods = 12, hoursPerPeriod = 24, 
                                        clusterMethod = 'hierarchical', 
                                        predefClusterOrder=aggregationEdem4.clusterOrder,
                                        predefClusterCenterIndices=aggregationEdem4.clusterCenterIndices)

In [20]:
typPeriodsEdem2Predef = aggregationEdem2Predef.createTypicalPeriods()
typPeriodsEdem4Predef = aggregationEdem4Predef.createTypicalPeriods()

In [21]:
predictedPeriodsEdem2Predef = aggregationEdem2Predef.predictOriginalData()
predictedPeriodsEdem4Predef = aggregationEdem4Predef.predictOriginalData()

### Show that Nothing Changes, if Cluster Order and Cluster Center Indeces are Predefined and Process is Repeated

In [22]:
aggregationEdem2.clusterOrder-aggregationEdem2Predef.clusterOrder

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [23]:
aggregationEdem4.clusterOrder-aggregationEdem4Predef.clusterOrder

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [24]:
edem2.mean(axis=0)

cluster_0    26.980326
cluster_1    33.282231
dtype: float64

In [25]:
predictedPeriodsEdem2Predef.mean(axis=0)

cluster_0    26.980326
cluster_1    33.282231
dtype: float64

In [26]:
edem4.mean(axis=0)

cluster_0    24.108759
cluster_1    10.753967
cluster_2     9.344134
cluster_3    16.055696
dtype: float64

In [27]:
predictedPeriodsEdem4Predef.mean(axis=0)

cluster_0    24.108759
cluster_1    10.753967
cluster_2     9.344134
cluster_3    16.055696
dtype: float64

### Show that Means Stay the Same, if 2 Regions are Clustered with the Cluster Order and Cluster Center Indeces from the Clustering of 4 Regions or with the Cluster Order of 4 Regions only

In [28]:
aggregationEdem2PredefFromEdem4 = tsam.TimeSeriesAggregation(edem2, noTypicalPeriods = 12, hoursPerPeriod = 24, 
                                        clusterMethod = 'hierarchical', 
                                        predefClusterOrder=aggregationEdem4.clusterOrder,
                                        predefClusterCenterIndices=aggregationEdem4.clusterCenterIndices)
aggregationEdem2PredefFromEdem4OrderOnly = tsam.TimeSeriesAggregation(edem2, noTypicalPeriods = 12, hoursPerPeriod = 24, 
                                                 clusterMethod = 'hierarchical', 
                                                 predefClusterOrder=aggregationEdem4.clusterOrder)

In [29]:
typPeriodsEdem2PredefFromEdem4 = aggregationEdem2PredefFromEdem4.createTypicalPeriods()
typPeriodsEdem2PredefFromEdem4OrderOnly = aggregationEdem2PredefFromEdem4OrderOnly.createTypicalPeriods()

In [30]:
predictedPeriodsEdem2PredefFromEdem4 = aggregationEdem2PredefFromEdem4.predictOriginalData()
predictedPeriodsEdem2PredefFromEdem4OrderOnly = aggregationEdem2PredefFromEdem4OrderOnly.predictOriginalData()

In [31]:
edem2.mean(axis=0)

cluster_0    26.980326
cluster_1    33.282231
dtype: float64

In [32]:
predictedPeriodsEdem2.mean(axis=0)

cluster_0    26.980326
cluster_1    33.282231
dtype: float64

In [33]:
predictedPeriodsEdem2Predef.mean(axis=0)

cluster_0    26.980326
cluster_1    33.282231
dtype: float64

In [34]:
predictedPeriodsEdem2PredefFromEdem4.mean(axis=0)

cluster_0    26.980326
cluster_1    33.282231
dtype: float64

In [35]:
predictedPeriodsEdem2PredefFromEdem4OrderOnly.mean(axis=0)

cluster_0    26.980326
cluster_1    33.282231
dtype: float64

However, the cluster order of the e-demand for two regions now differ from each other:

In [36]:
aggregationEdem2.clusterOrder-aggregationEdem2PredefFromEdem4.clusterOrder

array([  3,  -1,  -1,  -1,   2,   3,   0,  -9,  -9, -10, -10,  -2,   2,
        -9,  -5,  -6,  -6,  -6,  -2,   2,  -9,  -5,  -5,  -5,  -5,  -3,
         1,  -9,  -9,  -9,  -9,  -9,  -3,   2,  -1,  -5,  -6,  -6, -10,
        -2,   2, -10,  -6,  -6,   2,   2,  -3,   2,  -1,  -1,  -1,   2,
        -1,  -2,   2,  -1,   2,   2,  -1,  -1,  -3,  -1,   0,   0,  -5,
        -1,  -1,  -3,  -1,  -1,   2,  -1,  -1,  -1,  -3,  -1,   8,  -1,
        -1,  -1,  -1,  -3,   1,  -1,  -1,  -1,  -1,   2,  -1,  -1,  -1,
         3,  -1,  -1,  -1,  -3,  -2,   9,  -1,  -1,  -1,   3,   2,  -5,
         3,   9,   9,   3,   3,   2,  -5,  11,   3,   1,   9,   3,   2,
        -5,  11,   3,  -5,  11,  -5,   2,  -5,   3,   9,   3,  -5,   2,
         2,  -5,  11,   3,  -5,  -5,  -5,   2,  -1,  -1,  11,   3,  -5,
        -5,   2,  -1,  11,  -2,  -5,   2,   2,   2,   3,  11,   3,   3,
         3,   3,   2,   3,  11,   3,   3,   3,   2,   2,   3,  11,   3,
         3,   3,   3,   2,   3,  11,   3,   2,   3,   3,   2,   

In [37]:
aggregationEdem2.clusterOrder-aggregationEdem2PredefFromEdem4OrderOnly.clusterOrder

array([  3,  -1,  -1,  -1,   2,   3,   0,  -9,  -9, -10, -10,  -2,   2,
        -9,  -5,  -6,  -6,  -6,  -2,   2,  -9,  -5,  -5,  -5,  -5,  -3,
         1,  -9,  -9,  -9,  -9,  -9,  -3,   2,  -1,  -5,  -6,  -6, -10,
        -2,   2, -10,  -6,  -6,   2,   2,  -3,   2,  -1,  -1,  -1,   2,
        -1,  -2,   2,  -1,   2,   2,  -1,  -1,  -3,  -1,   0,   0,  -5,
        -1,  -1,  -3,  -1,  -1,   2,  -1,  -1,  -1,  -3,  -1,   8,  -1,
        -1,  -1,  -1,  -3,   1,  -1,  -1,  -1,  -1,   2,  -1,  -1,  -1,
         3,  -1,  -1,  -1,  -3,  -2,   9,  -1,  -1,  -1,   3,   2,  -5,
         3,   9,   9,   3,   3,   2,  -5,  11,   3,   1,   9,   3,   2,
        -5,  11,   3,  -5,  11,  -5,   2,  -5,   3,   9,   3,  -5,   2,
         2,  -5,  11,   3,  -5,  -5,  -5,   2,  -1,  -1,  11,   3,  -5,
        -5,   2,  -1,  11,  -2,  -5,   2,   2,   2,   3,  11,   3,   3,
         3,   3,   2,   3,  11,   3,   3,   3,   2,   2,   3,  11,   3,
         3,   3,   3,   2,   3,  11,   3,   2,   3,   3,   2,   

In [38]:
aggregationEdem2PredefFromEdem4.clusterOrder-aggregationEdem2PredefFromEdem4OrderOnly.clusterOrder

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

# Comparing Outputs

The first day of the e-demand time series for two regions is typical day number 10 (aggregationEdem2.clusterOrder), which is day number 194 of the original time series (aggregationEdem2.clusterCenterIndices):

In [39]:
edem2.iloc[194*24:195*24,:]

cluster_0  cluster_1
2050-07-14 00:30:00+01:00  20.730393  25.215748
2050-07-14 01:30:00+01:00  19.600621  23.910520
2050-07-14 02:30:00+01:00  18.819825  22.567316
2050-07-14 03:30:00+01:00  18.457561  21.721580
2050-07-14 04:30:00+01:00  18.281451  21.532690
2050-07-14 05:30:00+01:00  18.136017  21.563124
2050-07-14 06:30:00+01:00  17.959781  21.365360
2050-07-14 07:30:00+01:00  18.094826  21.818315
2050-07-14 08:30:00+01:00  19.032291  23.248850
2050-07-14 09:30:00+01:00  20.554235  25.344906
2050-07-14 10:30:00+01:00  21.601270  27.024871
2050-07-14 11:30:00+01:00  22.698795  28.370346
2050-07-14 12:30:00+01:00  23.531101  29.904040
2050-07-14 13:30:00+01:00  23.313057  29.460084
2050-07-14 14:30:00+01:00  22.545268  28.651873
2050-07-14 15:30:00+01:00  22.124805  27.914336
2050-07-14 16:30:00+01:00  21.721052  27.393089
2050-07-14 17:30:00+01:00  21.690826  27.168315
2050-07-14 18:30:00+01:00  22.078012  27.583129
2050-07-14 19:30:00+01:00  22.829659  28.060482
2050-07-14 20:30:00+01:00  22.962333  27.823808
2050-07-14 21:30:00+01:00  22.800990  27.632151
2050-07-14 22:30:00+01:00  22.349797  27.800344
2050-07-14 23:30:00+01:00  22.549281  27.838860

If you compare the day of the original time series to that of the predicted time series, it stays almost the same (small deviation due to rescaling):

In [40]:
predictedPeriodsEdem2.iloc[:24,:]

cluster_0  cluster_1
2050-01-01 00:30:00+01:00  20.738484  25.210873
2050-01-01 01:30:00+01:00  19.606369  23.906732
2050-01-01 02:30:00+01:00  18.823952  22.564648
2050-01-01 03:30:00+01:00  18.460937  21.719617
2050-01-01 04:30:00+01:00  18.284462  21.530884
2050-01-01 05:30:00+01:00  18.138726  21.561293
2050-01-01 06:30:00+01:00  17.962124  21.363694
2050-01-01 07:30:00+01:00  18.097449  21.816271
2050-01-01 08:30:00+01:00  19.036860  23.245613
2050-01-01 09:30:00+01:00  20.561961  25.339923
2050-01-01 10:30:00+01:00  21.611169  27.018488
2050-01-01 11:30:00+01:00  22.710971  28.362841
2050-01-01 12:30:00+01:00  23.545004  29.895257
2050-01-01 13:30:00+01:00  23.326508  29.451671
2050-01-01 14:30:00+01:00  22.557126  28.644133
2050-01-01 15:30:00+01:00  22.135790  27.907211
2050-01-01 16:30:00+01:00  21.731200  27.386399
2050-01-01 17:30:00+01:00  21.700910  27.161812
2050-01-01 18:30:00+01:00  22.088900  27.576281
2050-01-01 19:30:00+01:00  22.842106  28.053236
2050-01-01 20:30:00+01:00  22.975056  27.816759
2050-01-01 21:30:00+01:00  22.813379  27.625261
2050-01-01 22:30:00+01:00  22.361249  27.793314
2050-01-01 23:30:00+01:00  22.561147  27.831798

If you perdefine the cluster order and the indeces of the cluster centers which is derived from the first clustering for e-demand for two regions, you get exactly the same solution:

In [41]:
predictedPeriodsEdem2Predef.iloc[:24,:]

cluster_0  cluster_1
2050-01-01 00:30:00+01:00  20.738484  25.210873
2050-01-01 01:30:00+01:00  19.606369  23.906732
2050-01-01 02:30:00+01:00  18.823952  22.564648
2050-01-01 03:30:00+01:00  18.460937  21.719617
2050-01-01 04:30:00+01:00  18.284462  21.530884
2050-01-01 05:30:00+01:00  18.138726  21.561293
2050-01-01 06:30:00+01:00  17.962124  21.363694
2050-01-01 07:30:00+01:00  18.097449  21.816271
2050-01-01 08:30:00+01:00  19.036860  23.245613
2050-01-01 09:30:00+01:00  20.561961  25.339923
2050-01-01 10:30:00+01:00  21.611169  27.018488
2050-01-01 11:30:00+01:00  22.710971  28.362841
2050-01-01 12:30:00+01:00  23.545004  29.895257
2050-01-01 13:30:00+01:00  23.326508  29.451671
2050-01-01 14:30:00+01:00  22.557126  28.644133
2050-01-01 15:30:00+01:00  22.135790  27.907211
2050-01-01 16:30:00+01:00  21.731200  27.386399
2050-01-01 17:30:00+01:00  21.700910  27.161812
2050-01-01 18:30:00+01:00  22.088900  27.576281
2050-01-01 19:30:00+01:00  22.842106  28.053236
2050-01-01 20:30:00+01:00  22.975056  27.816759
2050-01-01 21:30:00+01:00  22.813379  27.625261
2050-01-01 22:30:00+01:00  22.361249  27.793314
2050-01-01 23:30:00+01:00  22.561147  27.831798

If we take the cluster order from the clustering of four regions, we have larger rescaling errors due to the fact that the cluster center indeces are not the medians anymore, but we find that the tenth and eleventh day (aggregationEdem4.clusterOrder) are represented by typical day number 10. So these days have to be the same in the predicted time series of two regions with predefined cluster order from the clustering of four regions: 

In [42]:
predictedPeriodsEdem2PredefFromEdem4.iloc[9*24:10*24,:]

cluster_0  cluster_1
2050-01-10 00:30:00+01:00  27.140637  34.206213
2050-01-10 01:30:00+01:00  25.810631  32.383121
2050-01-10 02:30:00+01:00  24.898556  31.278270
2050-01-10 03:30:00+01:00  24.416034  30.594953
2050-01-10 04:30:00+01:00  24.445175  30.648948
2050-01-10 05:30:00+01:00  24.790672  31.157545
2050-01-10 06:30:00+01:00  25.848493  32.677837
2050-01-10 07:30:00+01:00  28.893882  36.671958
2050-01-10 08:30:00+01:00  31.688235  40.082773
2050-01-10 09:30:00+01:00  32.446123  41.294368
2050-01-10 10:30:00+01:00  32.507137  41.510488
2050-01-10 11:30:00+01:00  33.018856  41.906240
2050-01-10 12:30:00+01:00  33.254322  41.941888
2050-01-10 13:30:00+01:00  32.927073  41.706055
2050-01-10 14:30:00+01:00  32.691873  41.304880
2050-01-10 15:30:00+01:00  32.193640  40.848123
2050-01-10 16:30:00+01:00  31.969496  40.340858
2050-01-10 17:30:00+01:00  31.589731  39.791315
2050-01-10 18:30:00+01:00  32.223288  41.238164
2050-01-10 19:30:00+01:00  33.236401  42.259747
2050-01-10 20:30:00+01:00  32.840345  41.068240
2050-01-10 21:30:00+01:00  30.917950  38.992465
2050-01-10 22:30:00+01:00  29.738518  37.439422
2050-01-10 23:30:00+01:00  28.958870  36.490135

In [43]:
predictedPeriodsEdem2PredefFromEdem4.iloc[10*24:11*24,:]

cluster_0  cluster_1
2050-01-11 00:30:00+01:00  27.140637  34.206213
2050-01-11 01:30:00+01:00  25.810631  32.383121
2050-01-11 02:30:00+01:00  24.898556  31.278270
2050-01-11 03:30:00+01:00  24.416034  30.594953
2050-01-11 04:30:00+01:00  24.445175  30.648948
2050-01-11 05:30:00+01:00  24.790672  31.157545
2050-01-11 06:30:00+01:00  25.848493  32.677837
2050-01-11 07:30:00+01:00  28.893882  36.671958
2050-01-11 08:30:00+01:00  31.688235  40.082773
2050-01-11 09:30:00+01:00  32.446123  41.294368
2050-01-11 10:30:00+01:00  32.507137  41.510488
2050-01-11 11:30:00+01:00  33.018856  41.906240
2050-01-11 12:30:00+01:00  33.254322  41.941888
2050-01-11 13:30:00+01:00  32.927073  41.706055
2050-01-11 14:30:00+01:00  32.691873  41.304880
2050-01-11 15:30:00+01:00  32.193640  40.848123
2050-01-11 16:30:00+01:00  31.969496  40.340858
2050-01-11 17:30:00+01:00  31.589731  39.791315
2050-01-11 18:30:00+01:00  32.223288  41.238164
2050-01-11 19:30:00+01:00  33.236401  42.259747
2050-01-11 20:30:00+01:00  32.840345  41.068240
2050-01-11 21:30:00+01:00  30.917950  38.992465
2050-01-11 22:30:00+01:00  29.738518  37.439422
2050-01-11 23:30:00+01:00  28.958870  36.490135

For the cluster order only, a new median is calculated of the given candidates belonging to each cluster center which is however close to the medians of the data clustered with four regions:

In [44]:
predictedPeriodsEdem2PredefFromEdem4OrderOnly.iloc[9*24:10*24,:]

cluster_0  cluster_1
2050-01-10 00:30:00+01:00  27.189840  34.181418
2050-01-10 01:30:00+01:00  25.853486  32.361372
2050-01-10 02:30:00+01:00  24.937059  31.258367
2050-01-10 03:30:00+01:00  24.452235  30.576191
2050-01-10 04:30:00+01:00  24.481514  30.630096
2050-01-10 05:30:00+01:00  24.828661  31.137843
2050-01-10 06:30:00+01:00  25.891529  32.655595
2050-01-10 07:30:00+01:00  28.951452  36.643042
2050-01-10 08:30:00+01:00  31.759141  40.048158
2050-01-10 09:30:00+01:00  32.520646  41.257729
2050-01-10 10:30:00+01:00  32.581951  41.473488
2050-01-10 11:30:00+01:00  33.096112  41.868579
2050-01-10 12:30:00+01:00  33.332702  41.904167
2050-01-10 13:30:00+01:00  33.003891  41.668728
2050-01-10 14:30:00+01:00  32.767568  41.268223
2050-01-10 15:30:00+01:00  32.266958  40.812229
2050-01-10 16:30:00+01:00  32.041744  40.305813
2050-01-10 17:30:00+01:00  31.660166  39.757188
2050-01-10 18:30:00+01:00  32.296747  41.201619
2050-01-10 19:30:00+01:00  33.314695  42.221495
2050-01-10 20:30:00+01:00  32.916749  41.031979
2050-01-10 21:30:00+01:00  30.985180  38.959673
2050-01-10 22:30:00+01:00  29.800119  37.409225
2050-01-10 23:30:00+01:00  29.016750  36.461523

In [45]:
predictedPeriodsEdem2PredefFromEdem4OrderOnly.iloc[10*24:11*24,:]

cluster_0  cluster_1
2050-01-11 00:30:00+01:00  27.189840  34.181418
2050-01-11 01:30:00+01:00  25.853486  32.361372
2050-01-11 02:30:00+01:00  24.937059  31.258367
2050-01-11 03:30:00+01:00  24.452235  30.576191
2050-01-11 04:30:00+01:00  24.481514  30.630096
2050-01-11 05:30:00+01:00  24.828661  31.137843
2050-01-11 06:30:00+01:00  25.891529  32.655595
2050-01-11 07:30:00+01:00  28.951452  36.643042
2050-01-11 08:30:00+01:00  31.759141  40.048158
2050-01-11 09:30:00+01:00  32.520646  41.257729
2050-01-11 10:30:00+01:00  32.581951  41.473488
2050-01-11 11:30:00+01:00  33.096112  41.868579
2050-01-11 12:30:00+01:00  33.332702  41.904167
2050-01-11 13:30:00+01:00  33.003891  41.668728
2050-01-11 14:30:00+01:00  32.767568  41.268223
2050-01-11 15:30:00+01:00  32.266958  40.812229
2050-01-11 16:30:00+01:00  32.041744  40.305813
2050-01-11 17:30:00+01:00  31.660166  39.757188
2050-01-11 18:30:00+01:00  32.296747  41.201619
2050-01-11 19:30:00+01:00  33.314695  42.221495
2050-01-11 20:30:00+01:00  32.916749  41.031979
2050-01-11 21:30:00+01:00  30.985180  38.959673
2050-01-11 22:30:00+01:00  29.800119  37.409225
2050-01-11 23:30:00+01:00  29.016750  36.461523

In [46]:
aggregationEdem4.clusterCenterIndices

[184, 79, 322, 19, 348, 64, 158, 250, 198, 20, 37, 110]

In [47]:
aggregationEdem2PredefFromEdem4.clusterCenterIndices

[184, 79, 322, 19, 348, 64, 158, 250, 198, 20, 37, 110]

In [48]:
aggregationEdem2PredefFromEdem4OrderOnly.clusterCenterIndices

[184, 77, 324, 19, 348, 64, 221, 236, 198, 20, 37, 110]